const join = (lines) => lines.join("\n");

export const courseCatalog = [
  {
    id: "request-tour",
    number: "00",
    category: "FULL STACK",
    title: "最初のrequestを観察する",
    summary: "コードを書く前に、ブラウザからRailsへ届くGETを実行して証拠を読む。",
    duration: "10分",
    writes: "コード変更なし",
    outcome: "method・path・status・responseを区別できる",
    accent: "teal",
    steps: [
      {
        id: "run-get",
        type: "request",
        title: "GET /api/v1/tasks を実行する",
        goal: "1回のrequestについて、method・path・status・response bodyを確認する。",
        instructions: [
          "「GETを実行」を押す。",
          "実行結果のRequest欄でmethodとpathを見る。",
          "Response欄でstatusとbodyの形を見る。",
        ],
        completion: "statusが200で、response bodyがtaskの配列になっている。",
        request: {
          method: "GET",
          path: "/api/v1/tasks",
          expectedStatus: 200,
          expectBody: "array",
        },
        primaryLabel: "GETを実行",
        terms: [
          ["HTTP request", "ブラウザからserverへ送る依頼。method・path・headers・bodyなどを持つ。"],
          ["status", "serverがrequestをどう処理したかを表す3桁の結果番号。"],
        ],
        preview: "request",
      },
      {
        id: "read-result",
        type: "read",
        title: "200が示す範囲を確認する",
        goal: "成功した場所と、まだ確認していない場所を分けて説明する。",
        instructions: [
          "下の実行経路を上から読む。",
          "200が返るまでに通ったfileとfunctionを確認する。",
          "画面の見た目だけでは分からない情報を確認する。",
        ],
        completion: "GETの入口からJSON responseまでの順番を読んだ。",
        code: join([
          "// frontend/src/api/tasks.js",
          "fetch(\"/api/v1/tasks\")",
          "",
          "# backend/config/routes.rb",
          "resources :tasks, only: %i[index create update destroy]",
          "",
          "# backend/app/controllers/api/v1/tasks_controller.rb",
          "def index",
          "  tasks = Task.order(created_at: :desc)",
          "  render json: tasks",
          "end",
        ]),
        explanation: "このendpointではControllerがTask.orderを実行してからJSONを返します。したがって200とtask配列を受け取れた場合、Route・Controller・DB query・JSON化まで完了しています。",
        preview: "request-flow",
      },
      {
        id: "request-quiz",
        type: "quiz",
        title: "証拠から正常範囲を判断する",
        goal: "statusとresponse bodyから、どこまで成功したか判断する。",
        question: "GET /api/v1/tasks が200で、response bodyがtask配列でした。最も正確な説明はどれですか？",
        choices: [
          "ReactのCSSだけが正常に読み込まれた",
          "requestがRailsへ届き、TasksController#indexがtask配列をJSONで返した",
          "POSTによるtask作成まで成功した",
          "すべての将来のrequestも必ず成功する",
        ],
        answer: 1,
        explanation: "200と配列は、このGET requestのRoute・Controller・DB query・responseが成功した証拠です。別のmethodや将来のrequestまでは保証しません。",
        completion: "成功した範囲を、現在のGET requestに限定して説明できる。",
      },
    ],
  },
  {
    id: "react-props",
    number: "01",
    category: "REACT",
    title: "propsで値を子Componentへ渡す",
    summary: "親が持つdoneとtotalを、子Componentの表示へつなぐ。",
    duration: "15分",
    writes: "関数引数とJSX",
    outcome: "propsの受け渡しをコード上で追える",
    accent: "blue",
    steps: [
      {
        id: "props-read",
        type: "read",
        title: "親から子へ渡る値を見る",
        goal: "propsを渡す側と受け取る側を区別する。",
        instructions: [
          "親Componentのdone={2}とtotal={3}を見る。",
          "子Componentのfunction引数を見る。",
          "受け取った値がJSXへ入る位置を見る。",
        ],
        completion: "渡す側はJSX属性、受け取る側はfunction引数だと確認した。",
        code: join([
          "// 親Component",
          "<TaskCount done={2} total={3} />",
          "",
          "// 子Component",
          "function TaskCount({ done, total }) {",
          "  return <p>完了: {done} / {total}</p>;",
          "}",
        ]),
        explanation: "propsは、親Componentが子Componentを呼ぶときに渡す値です。子Componentはfunctionの引数として受け取り、JSXから参照します。",
        preview: "props",
        terms: [
          ["Component", "UIの一部分を返すReactのfunction。"],
          ["props", "親Componentから子Componentへ渡される読み取り用の値。"],
        ],
      },
      {
        id: "props-edit",
        type: "edit",
        title: "固定値をpropsへ置き換える",
        goal: "TaskCountがdoneとtotalを受け取り、その値を表示する。",
        instructions: [
          "functionの引数でdoneとtotalを受け取る。",
          "JSXの0を{done}へ置き換える。",
          "もう一方の0を{total}へ置き換える。",
        ],
        completion: "5つの判定項目がすべて成功する。",
        targetFile: "sandbox/TaskCount.jsx",
        checker: "react-props",
        starterCode: join([
          "export default function TaskCount() {",
          "  return <p>完了: 0 / 0</p>;",
          "}",
        ]),
        preview: "props-result",
      },
      {
        id: "props-quiz",
        type: "quiz",
        title: "propsの変更元を判断する",
        goal: "表示値を変えるとき、親と子のどちらを見るか判断する。",
        question: "TaskCountへ渡されるtotalを3から4へ変えたい場合、最初に確認する場所はどこですか？",
        choices: [
          "子ComponentのCSS",
          "親Componentが<TaskCount total={...} />を呼んでいる場所",
          "Railsのmigration",
          "ブラウザのURL bar",
        ],
        answer: 1,
        explanation: "propsの値を決めるのは渡す側です。子Componentは受け取った値を表示します。",
        completion: "propsの値を決める場所が親Componentだと判断できる。",
      },
    ],
  },
  {
    id: "react-state",
    number: "02",
    category: "REACT",
    title: "stateをeventで更新する",
    summary: "buttonのclickからsetterを呼び、再レンダーで表示を変える。",
    duration: "15分",
    writes: "event handlerの1行",
    outcome: "event → setter → re-renderを説明できる",
    accent: "violet",
    steps: [
      {
        id: "state-read",
        type: "read",
        title: "state変更前後を操作する",
        goal: "stateの値と画面表示が対応していることを確認する。",
        instructions: [
          "右のbuttonを押す。",
          "openがfalseとtrueで切り替わることを見る。",
          "trueのときだけ説明文が表示されることを見る。",
        ],
        completion: "state変更によって表示条件の結果が変わることを確認した。",
        code: join([
          "const [open, setOpen] = useState(false);",
          "",
          "<button onClick={handleClick}>切り替える</button>",
          "{open && <p>説明文</p>}",
        ]),
        explanation: "stateはComponentが保持する値です。setterで更新するとReactが再レンダーし、新しいstateを使ってJSXを再評価します。",
        preview: "state",
        terms: [
          ["state", "Componentが再レンダーをまたいで保持する値。"],
          ["event handler", "clickやsubmitなどのevent発生時に呼ばれるfunction。"],
          ["re-render", "新しいstateやpropsを使ってComponentをもう一度評価すること。"],
        ],
      },
      {
        id: "state-edit",
        type: "edit",
        title: "handleClickでstateを反転する",
        goal: "clickするたびにopenがfalseとtrueで切り替わる。",
        instructions: [
          "handleClickの中へsetterを書く。",
          "現在のopenとは反対のbooleanを次の値にする。",
          "buttonのonClickは変更しない。",
        ],
        completion: "4つの判定項目がすべて成功する。",
        targetFile: "sandbox/HintButton.jsx",
        checker: "react-state",
        starterCode: join([
          "import { useState } from \"react\";",
          "",
          "export default function HintButton() {",
          "  const [open, setOpen] = useState(false);",
          "",
          "  function handleClick() {",
          "    // ここへstate更新を書く",
          "  }",
          "",
          "  return (",
          "    <>",
          "      <button onClick={handleClick}>説明を切り替える</button>",
          "      {open && <p>stateがtrueなので表示されています</p>}",
          "    </>",
          "  );",
          "}",
        ]),
        preview: "state-result",
      },
      {
        id: "state-quiz",
        type: "quiz",
        title: "setterを呼ばない場合を予測する",
        goal: "eventの発生とstate更新を別々に考える。",
        question: "buttonをclickしてhandleClickは呼ばれましたが、handleClick内でsetOpenを呼びませんでした。何が起きますか？",
        choices: [
          "Reactが自動的にopenを反転する",
          "openは変わらないため、表示も変わらない",
          "RailsへPOST requestが送られる",
          "Componentが自動的に削除される",
        ],
        answer: 1,
        explanation: "event handlerが呼ばれることとstateが変わることは別です。setterを呼ばなければopenは変わりません。",
        completion: "eventだけではstateが変わらないと説明できる。",
      },
    ],
  },
  {
    id: "rails-request",
    number: "03",
    category: "RAILS",
    title: "RouteからControllerへつなぐ",
    summary: "GET /api/v1/statsを受けるRouteとJSON responseを書く。",
    duration: "20分",
    writes: "RouteとController action",
    outcome: "URLから実行されるControllerを探せる",
    accent: "red",
    steps: [
      {
        id: "route-edit",
        type: "edit",
        title: "GET Routeを定義する",
        goal: "GET /api/v1/statsをStatsController#showへ接続する。",
        instructions: [
          "apiとv1のnamespaceは残す。",
          "get \"stats\"を追加する。",
          "to: \"stats#show\"を指定する。",
        ],
        completion: "RouteとController actionの2項目が成功する。",
        targetFile: "sandbox/config/routes.rb",
        checker: "rails-route",
        starterCode: join([
          "Rails.application.routes.draw do",
          "  namespace :api do",
          "    namespace :v1 do",
          "      # GET /api/v1/stats を追加する",
          "    end",
          "  end",
          "end",
        ]),
        preview: "route",
        terms: [
          ["Route", "HTTP methodとpathを、実行するController actionへ対応付ける設定。"],
          ["namespace", "URLとRuby moduleの階層をまとめるRailsの仕組み。"],
        ],
      },
      {
        id: "controller-edit",
        type: "edit",
        title: "JSON responseを返す",
        goal: "Taskの件数をcount keyへ入れて返す。",
        instructions: [
          "show actionを定義する。",
          "Task.countで件数を取得する。",
          "render json:で{ count: ... }を返す。",
        ],
        completion: "show・Task.count・JSON・count keyの4項目が成功する。",
        targetFile: "sandbox/app/controllers/api/v1/stats_controller.rb",
        checker: "rails-controller",
        starterCode: join([
          "module Api",
          "  module V1",
          "    class StatsController < ApplicationController",
          "      # show actionを追加する",
          "    end",
          "  end",
          "end",
        ]),
        preview: "controller",
      },
      {
        id: "route-read",
        type: "read",
        title: "methodとpathから実行先を読む",
        goal: "GET /api/v1/statsを見て、StatsController#showを特定する。",
        instructions: [
          "GETとstatsをRouteの定義に対応させる。",
          "stats#showをController名とaction名へ分ける。",
          "responseがJSONになる行を確認する。",
        ],
        completion: "method・path・Controller・actionを1本につないだ。",
        code: join([
          "GET /api/v1/stats",
          "        ↓",
          "get \"stats\", to: \"stats#show\"",
          "        ↓",
          "Api::V1::StatsController#show",
          "        ↓",
          "render json: { count: Task.count }",
        ]),
        explanation: "Routeはrequestの入口です。Controllerはrequestを処理し、renderでHTTP responseを作ります。",
        preview: "route-flow",
      },
      {
        id: "route-quiz",
        type: "quiz",
        title: "404の確認場所を選ぶ",
        goal: "Controllerが呼ばれる前の失敗を切り分ける。",
        question: "GET /api/v1/stats が404で、RailsログにStatsController#showが出ません。最初に確認する場所はどこですか？",
        choices: [
          "Reactの文字色",
          "config/routes.rbのmethodとpath",
          "DBのcreated_at",
          "TaskCountのprops",
        ],
        answer: 1,
        explanation: "Controllerへ到達していない404では、まずRouteのmethodとpathがrequestに一致するか確認します。",
        completion: "Controller到達前の404ではRouteを確認すると判断できる。",
      },
    ],
  },
  {
    id: "rails-validation",
    number: "04",
    category: "RAILS",
    title: "validationで不正な保存を止める",
    summary: "titleが空のTaskを保存せず、422とerrorsを返す流れを見る。",
    duration: "15分",
    writes: "Modelの1行",
    outcome: "validation失敗と422を結び付けられる",
    accent: "amber",
    steps: [
      {
        id: "validation-edit",
        type: "edit",
        title: "titleのpresenceを検証する",
        goal: "titleが空のTaskをvalidではない状態にする。",
        instructions: [
          "Task classの中へvalidatesを書く。",
          "検証対象を:titleにする。",
          "presence: trueを指定する。",
        ],
        completion: "titleとpresenceの2項目が成功する。",
        targetFile: "sandbox/app/models/task.rb",
        checker: "rails-validation",
        starterCode: join([
          "class Task < ApplicationRecord",
          "  # titleが空の保存を止めるvalidationを追加する",
          "end",
        ]),
        preview: "validation",
        terms: [
          ["Model", "DBのrecordと、保存時のruleを扱うRails class。"],
          ["validation", "保存前にdataがruleを満たすか検証する処理。"],
          ["422 Unprocessable Content", "requestの形は読めたが、内容がvalidationなどの条件を満たさない結果。"],
        ],
      },
      {
        id: "run-422",
        type: "request",
        title: "空のtitleをPOSTして422を見る",
        goal: "validation failureがHTTP responseへ変換されることを確認する。",
        instructions: [
          "「空titleをPOST」を押す。",
          "Request bodyのtask.titleが空文字であることを見る。",
          "status 422とerrors配列を見る。",
        ],
        completion: "statusが422で、response bodyにerrorsが含まれる。",
        request: {
          method: "POST",
          path: "/api/v1/tasks",
          body: { task: { title: "" } },
          expectedStatus: 422,
          expectBody: "errors",
        },
        primaryLabel: "空titleをPOST",
        preview: "validation-request",
      },
      {
        id: "validation-quiz",
        type: "quiz",
        title: "404と422を区別する",
        goal: "Route不一致とvalidation失敗をstatusから分ける。",
        question: "POST /api/v1/tasks が422でerrorsに「Title can't be blank」がありました。最も適切な判断はどれですか？",
        choices: [
          "Routeが見つからなかった",
          "requestはControllerまで届き、Model validationで保存できなかった",
          "Reactのbuttonがclickされなかった",
          "serverが必ず停止している",
        ],
        answer: 1,
        explanation: "422とModelのerrorsが返っているため、RouteとControllerを通り、保存時のvalidationで失敗しています。",
        completion: "422からvalidation failureまでの到達範囲を説明できる。",
      },
    ],
  },
  {
    id: "fullstack-post",
    number: "05",
    category: "FULL STACK",
    title: "POSTをReactからRailsへ通す",
    summary: "path・method・JSON bodyを直し、実際のRails APIへtaskを作る。",
    duration: "25分",
    writes: "fetch optionの3か所",
    outcome: "Reactの入力から201 responseまで追える",
    accent: "teal",
    steps: [
      {
        id: "post-flow",
        type: "read",
        title: "作成処理の実行順を読む",
        goal: "user操作から再レンダーまで、実際のidentifierで順番を追う。",
        instructions: [
          "TaskForm.handleSubmitを入口として読む。",
          "HTTP requestとRails側の処理を分ける。",
          "201 responseの後にsetTasksがあることを見る。",
        ],
        completion: "POST作成処理を7段階で確認した。",
        code: join([
          "TaskForm.handleSubmit",
          "  → App.handleAdd(title)",
          "  → fetch(\"/api/v1/tasks\", { method: \"POST\", body })",
          "  → TasksController#create",
          "  → Task#save / INSERT INTO tasks",
          "  → 201 Created + task JSON",
          "  → setTasks(...) / re-render",
        ]),
        explanation: "DBへ保存されたことと、現在のReact画面へ表示されたことは別の処理です。201の後にsetTasksを呼ぶことで、現在のstateにも作成結果を追加します。",
        preview: "fullstack",
      },
      {
        id: "fetch-edit",
        type: "edit",
        title: "壊れたfetchを修正する",
        goal: "Railsのcreate actionが期待するPOST requestを作る。",
        instructions: [
          "pathのtaskzをtasksへ直す。",
          "methodをGETからPOSTへ直す。",
          "bodyを{ task: { title } }の形にする。",
        ],
        completion: "path・POST・Content-Type・JSON変換・body形状の5項目が成功する。",
        targetFile: "sandbox/frontend/src/api/createTask.js",
        checker: "fullstack-fetch",
        starterCode: join([
          "export async function createTask(title) {",
          "  const response = await fetch(\"/api/v1/taskz\", {",
          "    method: \"GET\",",
          "    headers: { \"Content-Type\": \"application/json\" },",
          "    body: JSON.stringify({ title }),",
          "  });",
          "",
          "  return response.json();",
          "}",
        ]),
        preview: "fetch",
      },
      {
        id: "run-post",
        type: "request",
        title: "正しいPOSTを実際に送る",
        goal: "Railsへtaskを作成し、201と作成済みJSONを受け取る。",
        instructions: [
          "「POSTを実行」を押す。",
          "Request bodyがtask.titleの入れ子になっていることを見る。",
          "status 201とresponseのid・title・doneを見る。",
        ],
        completion: "statusが201で、response bodyに作成されたtaskのidがある。",
        request: {
          method: "POST",
          path: "/api/v1/tasks",
          body: { task: { title: "POSTの往復を確認する" } },
          expectedStatus: 201,
          expectBody: "task",
        },
        primaryLabel: "POSTを実行",
        preview: "post-request",
      },
      {
        id: "post-quiz",
        type: "quiz",
        title: "DBと画面stateを分ける",
        goal: "server保存とReact再レンダーが別の処理だと判断する。",
        question: "POSTが201でDB保存には成功しましたが、成功後にsetTasksを呼びませんでした。現在の画面はどうなりますか？",
        choices: [
          "DBにも保存されない",
          "DBには保存されるが、現在のReact stateが変わらないため画面には自動追加されない",
          "Railsが自動的にReact stateを書き換える",
          "必ず404になる",
        ],
        answer: 1,
        explanation: "201はserver側の作成成功です。現在の画面へ反映するには、responseを使ってReact stateも更新する必要があります。",
        completion: "server保存とclient state更新を別々に説明できる。",
      },
    ],
  },
  {
    id: "debug-status",
    number: "06",
    category: "DEBUG",
    title: "404と422を証拠から切り分ける",
    summary: "推測でコードを直さず、Networkのstatusとresponseから故障層を絞る。",
    duration: "15分",
    writes: "コード変更なし",
    outcome: "次に見るfileをstatusから決められる",
    accent: "slate",
    steps: [
      {
        id: "run-404",
        type: "request",
        title: "間違ったpathで404を発生させる",
        goal: "Routeに一致しないrequestの結果を観察する。",
        instructions: [
          "「誤ったpathへGET」を押す。",
          "Request pathが/api/v1/taskzであることを見る。",
          "status 404を確認する。",
        ],
        completion: "statusが404になり、正しい/tasksとの差を見つける。",
        request: {
          method: "GET",
          path: "/api/v1/taskz",
          expectedStatus: 404,
          expectBody: "any",
        },
        primaryLabel: "誤ったpathへGET",
        preview: "debug-404",
      },
      {
        id: "diagnose-404",
        type: "quiz",
        title: "404の次に見る場所を決める",
        goal: "requestがControllerへ到達する前の問題を疑う。",
        question: "GET /api/v1/taskz が404でした。最初に比較するべきものはどれですか？",
        choices: [
          "NetworkのRequest URLとconfig/routes.rbのpath",
          "Task modelのlength validation",
          "Reactのfont-size",
          "DBのupdated_at",
        ],
        answer: 0,
        explanation: "404では、まずrequestのmethod・pathがRouteと一致するかを比較します。taskzとtasksの1文字差が証拠です。",
        completion: "404ではmethod・pathとRouteを最初に比較できる。",
      },
      {
        id: "run-debug-422",
        type: "request",
        title: "正しいpathで不正なdataを送る",
        goal: "Routeは一致するが内容で失敗する422を404と比較する。",
        instructions: [
          "「空titleをPOST」を押す。",
          "pathが正しい/api/v1/tasksであることを見る。",
          "status 422とerrorsを見る。",
        ],
        completion: "正しいpathでもdataの条件により422になることを確認する。",
        request: {
          method: "POST",
          path: "/api/v1/tasks",
          body: { task: { title: "" } },
          expectedStatus: 422,
          expectBody: "errors",
        },
        primaryLabel: "空titleをPOST",
        preview: "debug-422",
      },
      {
        id: "debug-quiz",
        type: "quiz",
        title: "statusから調査順を決める",
        goal: "404と422で最初に見る場所を変える。",
        question: "最も適切な調査順の組み合わせはどれですか？",
        choices: [
          "404→Model validation、422→CSS",
          "404→Routeのmethod/path、422→request bodyとModel errors",
          "404→DB削除、422→browser再起動",
          "どちらも最初に全fileを書き換える",
        ],
        answer: 1,
        explanation: "404は入口の一致、422は読めたrequest内容の条件を調べます。statusに応じて確認場所を狭めます。",
        completion: "404と422で最初に見る証拠を言い分けられる。",
      },
    ],
  },
];

export function findCourse(courseId) {
  return courseCatalog.find((course) => course.id === courseId) ?? courseCatalog[0];
}
